import { useEffect, useRef, useState, type FormEvent } from 'react'
import type { CustomShoppingList, ShoppingItem, UserData, Recipe } from '../types'
import { generateShoppingList } from '../lib/calculations'
import { EmptyState } from '../components/States'

export function ShoppingList({ recipes, data, save }: { recipes: Recipe[]; data: UserData; save: (patch: Partial<UserData>) => Promise<boolean> }) {
  const [name, setName] = useState(''); const [quantity, setQuantity] = useState(''); const [unit, setUnit] = useState('buc'); const [listName, setListName] = useState(''); const [activeList, setActiveList] = useState<string | null>(null); const [customItem, setCustomItem] = useState(''); const [feedback, setFeedback] = useState<string | null>(null)
  const inputKey = JSON.stringify({ plan:data.meal_plan, pantry:data.pantry, recipes:recipes.map(({id,servings,ingredients})=>({id,servings,ingredients})) }); const previousKey = useRef('')
  const regenerate = async (showFeedback = false) => { const next = generateShoppingList(data.meal_plan, recipes, data.pantry, data.shopping_list); const saved = await save({ shopping_list: next }); if (showFeedback) setFeedback(saved ? `Lista de cumpărături a fost actualizată: ${next.length} produse.` : 'Lista nu a putut fi actualizată. Încearcă din nou.') }
  useEffect(() => { if (previousKey.current !== inputKey) { previousKey.current = inputKey; void regenerate() } }, [inputKey])
  const updateFood = (id: string, patch: Partial<ShoppingItem>) => void save({ shopping_list:data.shopping_list.map((item) => item.id === id ? { ...item, ...patch } : item) })
  const addFood = (event: FormEvent) => { event.preventDefault(); const value=Number(quantity); if (!name.trim() || value<=0) return; void save({ shopping_list:[...data.shopping_list,{id:crypto.randomUUID(),name:name.trim(),quantity:value,unit,manual:true,checked:false}] }); setName(''); setQuantity('') }
  const createList = (event: FormEvent) => { event.preventDefault(); if (!listName.trim()) return; const next:CustomShoppingList={id:crypto.randomUUID(),name:listName.trim(),items:[]}; void save({custom_lists:[...data.custom_lists,next]}); setActiveList(next.id); setListName('') }
  const current = data.custom_lists.find((list) => list.id === activeList)
  const updateCustom = (items: ShoppingItem[]) => current && void save({ custom_lists:data.custom_lists.map((list) => list.id === current.id ? {...list,items} : list) })
  const addCustom = (event: FormEvent) => { event.preventDefault(); if (!current || !customItem.trim()) return; updateCustom([...current.items,{id:crypto.randomUUID(),name:customItem.trim(),quantity:1,unit:'buc',manual:true,checked:false}]); setCustomItem('') }
  return <><header><span className="eyebrow">CUMPĂRĂTURI</span><h1>Lista ta</h1></header><div className="actions"><button onClick={() => void regenerate(true)}>↻ Actualizează lista cumpărături</button>{data.meal_plan.length===0&&<span>Nu ai planificat încă nicio masă.</span>}</div>{feedback&&<p className="update-feedback" role="status">{feedback}</p>}<form className="inline-form card" onSubmit={addFood}><input placeholder="Produs alimentar manual" value={name} onChange={e=>setName(e.target.value)} required/><input type="number" min="0.01" step="any" placeholder="Cantitate" value={quantity} onChange={e=>setQuantity(e.target.value)} required/><input value={unit} onChange={e=>setUnit(e.target.value)} required/><button>Adaugă</button></form><section className="card list">{data.shopping_list.length ? data.shopping_list.map((item)=><div key={item.id} className={item.checked?'checked':''}><input type="checkbox" checked={item.checked} onChange={e=>updateFood(item.id,{checked:e.target.checked})}/><strong>{item.name}</strong><input type="number" min="0" step="any" value={item.quantity} onChange={e=>updateFood(item.id,{quantity:Number(e.target.value)||0})}/><input value={item.unit} onChange={e=>updateFood(item.id,{unit:e.target.value})}/><button className="danger" onClick={()=>void save({shopping_list:data.shopping_list.filter((entry)=>entry.id!==item.id)})}>Șterge</button></div>) : <EmptyState>Lista de cumpărături este goală.</EmptyState>}</section><section className="custom-lists"><h2>Liste personale</h2><p>De exemplu: produse de curățenie, bricolaj sau animale.</p><form className="inline-form" onSubmit={createList}><input placeholder="Numele listei noi" value={listName} onChange={e=>setListName(e.target.value)}/><button>Creează listă</button></form>{data.custom_lists.length>0&&<select value={activeList||''} onChange={e=>setActiveList(e.target.value||null)}><option value="">Alege o listă</option>{data.custom_lists.map(list=><option value={list.id} key={list.id}>{list.name}</option>)}</select>}{current&&<section className="card personal-list"><h3>{current.name}</h3><form className="inline-form" onSubmit={addCustom}><input placeholder="Adaugă produs" value={customItem} onChange={e=>setCustomItem(e.target.value)}/><button>Adaugă</button></form>{current.items.length?current.items.map(item=><div className={item.checked?'checked':''} key={item.id}><input type="checkbox" checked={item.checked} onChange={e=>updateCustom(current.items.map(entry=>entry.id===item.id?{...entry,checked:e.target.checked}:entry))}/><strong>{item.name}</strong><button className="danger" onClick={()=>updateCustom(current.items.filter(entry=>entry.id!==item.id))}>Șterge</button></div>):<EmptyState>Lista este goală.</EmptyState>}</section>}</section></>
}
